### PR TITLE
Use `message` function to write to *Messages* buffer

### PR DESCRIPTION
**Pull request by telotortium**
\*Messages\* buffer is read-only and thus cannot be written to with the
`insert` function.

### CODE REVIEW

**Comment by jordonbiondo** [comment]
Thanks @telotortium, I’ll give it a look, sorry I missed this at first. Funny enough this was written before messages was read only which was itself is an old change!

**Comment by jordonbiondo** [comment]
@telotortium I fixed the read-only issue you brought up in a slightly different way so I'll close this for now.

I see you also made some changes to the way clog looks up the calling function. If you would like I'd merge a PR with that change based on latest master.

**Comment by telotortium** [comment]
Thanks!

**Comment by telotortium** [comment]
Please change the way clog looks up the calling function - I've already had to work around it locally, because I was running into an infinite recursion.

**Pull request closed without merging**
